# NUMPY ARRAYS 

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
from numpy import random

# 3. Numpy Array Manipulation (Hint: Use knowledge learnt in Mathematical Computing).
(a) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (Hint: create a 5x3 and 3x2 matrices
and peform matrix multiplication).


(b) Create a 3x3 identity matrix


(c) Create a vector with values ranging from 10 to 49).


(d) Create a null vector of size 10.


(e) Create a 3x3x3 array with random values


(f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


(g) Normalize a 5x5 random matrix


(h) How to get the dates of yesterday, today and tomorrow?


(i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your approach

# Solutions

# (a) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (Hint: create a 5x3 and 3x2 matrices and peform matrix multiplication).

In [7]:
matrix1 = np.array([[[1,2,3],[3,4,5],[2,3,4],[3,2,1],[2,3,3,]]])
print(matrix1)



[[[1 2 3]
  [3 4 5]
  [2 3 4]
  [3 2 1]
  [2 3 3]]]


In [10]:
matrix2 = np.array([[[1,2],[3,4],[3,5]]])
print(matrix2)

[[[1 2]
  [3 4]
  [3 5]]]


In [11]:
product = np.dot(matrix1,matrix2)
product

array([[[[16, 25]],

        [[30, 47]],

        [[23, 36]],

        [[12, 19]],

        [[20, 31]]]])

# (b) Create a 3x3 identity matrix

In [24]:
identity_matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(identity_matrix) # This is a matrix whose all diagonal elements are equal to 1.It is also known as a unit matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# (c) Create a vector with values ranging from 10 to 49).

In [17]:
vector = np.array([10,11,12,13,14,15])
vector

array([10, 11, 12, 13, 14, 15])

# (d) Create a null vector of size 10.

In [23]:
vector2 = np.array([0,0,0,0,0,0,0,0,0,0])
vector2 # This is a matrix whose all elements are zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# (e) Create a 3x3x3 array with random values

In [22]:
array = np.random.rand(3,3,3)
array # This is a 3x3 matrix 3 times

array([[[3.70835116e-01, 4.94599196e-01, 5.83845168e-01],
        [1.16472442e-02, 9.17636042e-01, 7.82201759e-01],
        [7.45426429e-01, 5.27768194e-01, 5.86701972e-01]],

       [[6.06183512e-04, 5.23151713e-01, 3.39266919e-01],
        [8.07695493e-01, 2.75452128e-01, 6.70428591e-01],
        [8.31108438e-01, 2.41676868e-01, 8.98815625e-01]],

       [[9.93969885e-01, 5.27093722e-02, 2.63803313e-01],
        [5.40320674e-01, 2.31436297e-01, 1.25363037e-01],
        [7.12957036e-01, 9.82292333e-01, 2.65959368e-01]]])

# (f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
matrix = np.array([[[0,0,0,0,0],[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,4,0]]])
matrix # This means the matrix whos elements below the diagonal are 1,2,3,4. and all othe elements are zeros

array([[[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]]])

# (g) Normalize a 5x5 random matrix

In [28]:
random_matrix = np.random.rand(5,5)
random_matrix # First craete a random 5x5 matrix

array([[0.88828187, 0.59877649, 0.89136989, 0.67947435, 0.63313449],
       [0.82215778, 0.30448988, 0.895492  , 0.50378233, 0.44745519],
       [0.23234028, 0.08921615, 0.61541396, 0.86153791, 0.57993227],
       [0.19526687, 0.99865458, 0.55897109, 0.55074356, 0.71566198],
       [0.23163501, 0.13688729, 0.0056539 , 0.60344724, 0.95416408]])

In [29]:
normalised_matrix = (random_matrix/matrix.max())
normalised_matrix # Then to normalis means dividing the original matrix with the maximum values of that same matrix

array([[0.22207047, 0.14969412, 0.22284247, 0.16986859, 0.15828362],
       [0.20553945, 0.07612247, 0.223873  , 0.12594558, 0.1118638 ],
       [0.05808507, 0.02230404, 0.15385349, 0.21538448, 0.14498307],
       [0.04881672, 0.24966364, 0.13974277, 0.13768589, 0.17891549],
       [0.05790875, 0.03422182, 0.00141347, 0.15086181, 0.23854102]])

# (h) How to get the dates of yesterday, today and tomorrow?

# (i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your approach